# Setup
title: ivanOS
tagline: 🌻 my digital garden -- a place for my ideas to grow and bloom 🌱
url: https://hiivan.github.io/
paginate: 1
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Google Analytics tracking
ga_analytics: UA-171125265-1

# Specify the author for blog posts
author:
  name: Ivan Ang
  url: https://twitter.com/hiiiivan
  email: ivanang47@gmail.com

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/essentialenemy/noir
