# Setup
title: ivanOS
tagline: my digital garden — a place for my ideas to grow and blossom.
url: https://www.ivan-ang.com
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Ivan Ang
  url: https://twitter.com/hiiiivan
  email: ivanang47@gmail.com

#Twitter cards
twitter:
  username: hiiiivan
  card: summary

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/essentialenemy/noir
